apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: mediconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: 347351796859.dkr.ecr.us-east-1.amazonaws.com/mediconnect-admin:latest
          ports:
            - containerPort: 80