apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: mediconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 347351796859.dkr.ecr.us-east-1.amazonaws.com/mediconnect-frontend:latest
          ports:
            - containerPort: 80