name: Build and Push Frontend

on:
  push:
    branches:
      - feature/aws-migration
    paths:
      - 'fronted/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mediconnect-frontend
          IMAGE_TAG: latest
        run: |
          docker build \
            --build-arg VITE_BACKEND_URL='${{ secrets.VITE_BACKEND_URL }}' \
            --build-arg VITE_RAZORPAY_KEY_ID='${{ secrets.VITE_RAZORPAY_KEY_ID }}' \
            --build-arg VITE_AGORA_APP_ID='${{ secrets.VITE_AGORA_APP_ID }}' \
            --build-arg VITE_SOCKET_URL='${{ secrets.VITE_SOCKET_URL }}' \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./fronted
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG